### PR TITLE
Updating jsftp and its .raw api

### PR DESCRIPTION
**Pull request by Psykoral**
Resolves https://github.com/Robert-W/grunt-ftp-push/issues/50

References: 
https://github.com/sergi/jsftp/issues/226
https://github.com/sergi/jsftp/commit/35a8edd6e1132898590d585a415c521df000cb58

### CODE REVIEW

**Comment by Robert-W** [comment]
Thanks, looks good to me.

**Comment by Psykoral** [comment]
Thanks! I don't see this tied to a specific milestone. Is this going to be in 1.21, or something to that effect?

**Comment by Robert-W** [comment]
This will be tied to 1.2.1. Unfortunately I do not have the time to actively maintain this project anymore so there are no upcoming milestones and if any interested parties want to take ownership of this project I am more than willing to add owners/collaborators.  I try to keep an eye out for any PR's that look ready to go and merge them as soon as I can but that's about all that is going into this.

I can cut a release for this tonight or tomorrow night for version 1.2.1.

**Comment by Psykoral** [comment]
Thanks Robert, totally understand. I still find it very handy and use it frequently, I'd be happy to become a collaborator on it and help maintain it. 

Otherwise, tonight is plenty quick for a release 👍 . Thanks a bunch!

**Comment by Robert-W** [comment]
Ok sounds good, I just added you as a collaborator. Thanks for contributing back.

**Pull request merged**
